version: "3.7"
services:
  user_service:
    build:
      context: .
      dockerfile: Dockerfile
    image: aristidesama2/venteapimaven_3of3_api:v1
    container_name: venteapimaven_api
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mongo_db
  mongo_db:
    build:
      context: .
      dockerfile: Dockerfile-mongodb
    image: aristidesama2/venteapimaven_1of3_mongodb:v1
    container_name: venteapimaven_mongo_db_1
    restart: always
    ports:
      - 27017:27017
  mongo_shell:
    build:
      context: .
      dockerfile: Dockerfile-monitor-db
    image: aristidesama2/venteapimaven_2of3_monitor-db:v1
    container_name: venteapimaven_monitor-db