version: "3.7"
services:
  user_service:
    build: .
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mongo_db
  mongo_db:
    build:
      context: .
      dockerfile: Dockerfile-mongodb
    container_name: venteapimaven_mongo_db_1
    restart: always
    ports:
      - 27017:27017
  mongo_shell:
    image: "mongo:4.4.3"
    depends_on:
      - mongo_db